before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.coursier
    - $HOME/.ivy2/cache

language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
  - 2.13.0-M4

jdk:
  - oraclejdk8

env:
  global:
    - COURSIER_PROGRESS=0
